Updated headers and navbar
ASU-CodeDevils/codedevils.org pull request #18
Opened 2022-12-17 17:35 UTC by fernandonevarez

I restructured the fundamentals of the filing systems to a new design to allow custom headers for each page. However, I also updated the navbar to look like what we had on the old website. Additionally, I made the navbar and headers responsive for both mobile and desktop.

2022-12-17 18:06 UTC, reharri7 requested changes
Overall this is good. I haven't used react in over 2 years so I'm a little foggy on the state management stuff and I'm not up to date with how things work in react nowadays. Check with ESLint and make sure those rules are being enforced. Fix the minor issues in the code and will be able to merge

2022-12-17 18:06 UTC, reharri7 commented on src/components/headers/_headerLayout.tsx
> +import React, { useEffect, useState } from "react";
These are probably fine, but ESLint may prefer ' over ". If it does complain about it then they will have to change

2022-12-17 18:06 UTC, reharri7 commented on src/components/headers/_headerLayout.tsx
> +const PageHedaer = () => {
Misspelling

2022-12-17 18:06 UTC, reharri7 commented on src/components/headers/contact.tsx
> +        Get in touch and let us know how we can help you with your cooking needs. Fill out the form and we&#180;ll be in touch as soon as possible.
Cooking => coding?

2022-12-17 18:06 UTC, reharri7 commented on src/components/page_layout/_pageLayout.tsx
> +      <PageHedaer />
Misspelling

2022-12-17 18:06 UTC, reharri7 commented on src/components/page_layout/navbars/_navbarLayout.tsx
> +      if (typeof window !== "undefined" && window.innerWidth < 768) {
Use 
```suggestion
      SetIsMobile(resultOfThisBoolean)
```

2022-12-17 18:06 UTC, reharri7 commented on src/pages/_app.tsx
> +        {/* This becomes the chidlren of the layout component because it's nested within the layout component*/}
Misspelling

2022-12-17 18:06 UTC, reharri7 commented on src/styles/components/page_layout/navbars/mobile.module.scss
> +          // styles that will be appied to bothe the icon and the text
Misspelling

2022-12-17 18:06 UTC, reharri7 commented on src/styles/components/page_layout/navbars/mobile.module.scss
> +    // left: 0;
Remove unused style

2022-12-17 18:06 UTC, reharri7 commented on src/styles/components/page_layout/navbars/mobile.module.scss
> +    // background: $asu_grey;
Removed unused style

2022-12-17 18:06 UTC, reharri7 commented on src/styles/components/page_layout/navbars/mobile.module.scss
> +  }
Remove unused style

2022-12-17 18:06 UTC, reharri7 commented on src/styles/components/page_layout/pageDivider.module.scss
> +// another svg styles
Remove all above unused styles

2022-12-17 18:06 UTC, reharri7 commented on src/styles/components/page_layout/pageDivider.module.scss
> +// another svg styles
You can leave a commented out note with which commit number they were removed in

2022-12-17 19:35 UTC, fernandonevarez commented
Alright, all the changes are done except for one 
- ` if (typeof window !== "undefined" && window.innerWidth < 768) {
      SetIsMobile(resultOfThisBoolean) }`

Can't seem to understand the difference between what you're asking for me to change to what I have already.

2022-12-18 01:08 UTC, fernandonevarez commented on src/components/headers/_headerLayout.tsx
> +import React, { useEffect, useState } from "react";
EsLint has no problem with it.

2022-12-18 01:14 UTC, merged